//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNotes.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyNotes.Localization.LocalizeResource", typeof(LocalizeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string AddNoteMenuItem {
            get {
                return ResourceManager.GetString("AddNoteMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить заметку.
        /// </summary>
        public static string AddNoteToolTip {
            get {
                return ResourceManager.GetString("AddNoteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string CancelBtn {
            get {
                return ResourceManager.GetString("CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string CancelBtnRegWindow {
            get {
                return ResourceManager.GetString("CancelBtnRegWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите пароль:.
        /// </summary>
        public static string ConfirmPasswordLblRegWindow {
            get {
                return ResourceManager.GetString("ConfirmPasswordLblRegWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Содержимое:.
        /// </summary>
        public static string ContentLbl {
            get {
                return ResourceManager.GetString("ContentLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать аккаунт.
        /// </summary>
        public static string CreateAnAccount {
            get {
                return ResourceManager.GetString("CreateAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string DeleteNoteMenuItem {
            get {
                return ResourceManager.GetString("DeleteNoteMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить заметку.
        /// </summary>
        public static string DeleteNoteToolTip {
            get {
                return ResourceManager.GetString("DeleteNoteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string EditNoteMenuItem {
            get {
                return ResourceManager.GetString("EditNoteMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать заметку.
        /// </summary>
        public static string EditNoteToolTip {
            get {
                return ResourceManager.GetString("EditNoteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная почта:.
        /// </summary>
        public static string EmailLbl {
            get {
                return ResourceManager.GetString("EmailLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная почта:.
        /// </summary>
        public static string EmailLblRegWindow {
            get {
                return ResourceManager.GetString("EmailLblRegWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите содержимое.
        /// </summary>
        public static string EnterContent {
            get {
                return ResourceManager.GetString("EnterContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите свою электронную почту.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите своё имя.
        /// </summary>
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите пароль.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите свою фамилию.
        /// </summary>
        public static string EnterSurname {
            get {
                return ResourceManager.GetString("EnterSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, введите заголовок.
        /// </summary>
        public static string EnterTitle {
            get {
                return ResourceManager.GetString("EnterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        public static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание.
        /// </summary>
        public static string ExclamationCaption {
            get {
                return ResourceManager.GetString("ExclamationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректная электронная почта.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык:.
        /// </summary>
        public static string LanguageLbl {
            get {
                return ResourceManager.GetString("LanguageLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены что хотите удалить эту заметку?.
        /// </summary>
        public static string MessageAboutDeletingNotes {
            get {
                return ResourceManager.GetString("MessageAboutDeletingNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение.
        /// </summary>
        public static string MessageCaption {
            get {
                return ResourceManager.GetString("MessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для того чтобы изменения вступили в силу, нужно перезапустить приложение.
        /// </summary>
        public static string MessageSaveLanguage {
            get {
                return ResourceManager.GetString("MessageSaveLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя:.
        /// </summary>
        public static string NameLblRegWindow {
            get {
                return ResourceManager.GetString("NameLblRegWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет:.
        /// </summary>
        public static string NoteColorLbl {
            get {
                return ResourceManager.GetString("NoteColorLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть настройки.
        /// </summary>
        public static string OpenSettingsToolTip {
            get {
                return ResourceManager.GetString("OpenSettingsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли не совпадают.
        /// </summary>
        public static string PasswordDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль:.
        /// </summary>
        public static string PasswordLbl {
            get {
                return ResourceManager.GetString("PasswordLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль:.
        /// </summary>
        public static string PasswordLblRegWindow {
            get {
                return ResourceManager.GetString("PasswordLblRegWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопрос.
        /// </summary>
        public static string QuestionCaption {
            get {
                return ResourceManager.GetString("QuestionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string RegistrationBtnRegWindow {
            get {
                return ResourceManager.GetString("RegistrationBtnRegWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск:.
        /// </summary>
        public static string SearchLBL {
            get {
                return ResourceManager.GetString("SearchLBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите текст для поиска.
        /// </summary>
        public static string SearchToolTip {
            get {
                return ResourceManager.GetString("SearchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string SignInBtn {
            get {
                return ResourceManager.GetString("SignInBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия:.
        /// </summary>
        public static string SurnameLblRegWindow {
            get {
                return ResourceManager.GetString("SurnameLblRegWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Notes - Авторизация.
        /// </summary>
        public static string TitleAuthorizationWindow {
            get {
                return ResourceManager.GetString("TitleAuthorizationWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок:.
        /// </summary>
        public static string TitleLbl {
            get {
                return ResourceManager.GetString("TitleLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Notes - Создание заметки.
        /// </summary>
        public static string TitleNoteEditorWindow_Adding {
            get {
                return ResourceManager.GetString("TitleNoteEditorWindow_Adding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Notes - Редактирование заметки .
        /// </summary>
        public static string TitleNoteEditorWindow_Editing {
            get {
                return ResourceManager.GetString("TitleNoteEditorWindow_Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Notes - Регистрация.
        /// </summary>
        public static string TitleRegistrationWindow {
            get {
                return ResourceManager.GetString("TitleRegistrationWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Notes - Настройки.
        /// </summary>
        public static string TitleSettingsWindow {
            get {
                return ResourceManager.GetString("TitleSettingsWindow", resourceCulture);
            }
        }
    }
}
