//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyNotes.MyNotesServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyNotesServiceReference.IRegistration")]
    public interface IRegistration {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistration/NewUserRegistration", ReplyAction="http://tempuri.org/IRegistration/NewUserRegistrationResponse")]
        int NewUserRegistration(string name, string surname, string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistration/NewUserRegistration", ReplyAction="http://tempuri.org/IRegistration/NewUserRegistrationResponse")]
        System.Threading.Tasks.Task<int> NewUserRegistrationAsync(string name, string surname, string email, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegistrationChannel : MyNotes.MyNotesServiceReference.IRegistration, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrationClient : System.ServiceModel.ClientBase<MyNotes.MyNotesServiceReference.IRegistration>, MyNotes.MyNotesServiceReference.IRegistration {
        
        public RegistrationClient() {
        }
        
        public RegistrationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistrationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int NewUserRegistration(string name, string surname, string email, string password) {
            return base.Channel.NewUserRegistration(name, surname, email, password);
        }
        
        public System.Threading.Tasks.Task<int> NewUserRegistrationAsync(string name, string surname, string email, string password) {
            return base.Channel.NewUserRegistrationAsync(name, surname, email, password);
        }
    }
}
